### ISSUE TITLE
Custom IContainerNameResolver leads to 400 errors

### ISSUE THREAD

**Issue by FrancoisM** [Azure/azure-mobile-apps-net-files-server#7]
Hi,

I first raised the issue in a sample project using that Library but I think it is more relevant here. See original post:
https://github.com/Azure-Samples/app-service-mobile-dotnet-todo-list-files/issues/6

I'm trying to implement IContainerNameResolver so I can choose the container name pattern. My first implementation was a copy/paste of the default one used in that project. Then I just changed "-" with "_" or "/" in GetDefaultContainerName and now I have http 400 errors.

However, any other combinations without chars such as "/" or "_" or "'(" etc would work.

Then I found this:
https://msdn.microsoft.com/en-us/library/azure/dd135715.aspx

It says there are restrictions on the container name characters.
However "/" can be used in blob name so I'll try to move it there.

**Comment by fabiocav** [comment]
@FrancoisM this is expected behavior when working with Azure Blob storage. Ultimately, the resolver needs use a naming convention that is supported by the underlying provider. One enhancement we could make here is to update the AzureStorageProvider to provide a more meaningful message if invalid names are used.
